blank_issues_enabled: false
contact_links:
  - name: 🙋 Ask questions on Discord
    url: https://discord.gg/7T6fdmp3
    about: Ask general questions about DeployStack or Deplpying your app with DeployStack