---
name: 🛠️ Feature Request
description: Suggest an idea to help us improve DeployStack
title: "[Feature]: "
labels:
  - "ty: feature"

body:
  - type: markdown
    attributes:
      value: >
        **Thank you for helping improve DeployStack!** 
        
        Before submitting, please check if someone else has already suggested this feature by searching our [existing issues](https://github.com/deploystackio/feedback/issues?q=is%3Aissue+label%3Aty%3Afeature+).

  - type: textarea
    attributes:
      label: Description
      description: |
        A clear and concise description of the feature you're interested in.
      value: |
        <!--- Describe your feature here --->
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggested Solution
      description: >
        Describe the solution you'd like. A clear and concise description of what you want to happen. If you have
        considered alternatives, please describe them.
      value: |
        <!--- Describe your solution here --->
    validations:
      required: false