name: Protect Labels
on:
  issues:
    types: [labeled, unlabeled]

# Add this permissions block
permissions:
  issues: write

jobs:
  protect-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const protectedLabels = ['status: accepted', 'status: in-progress'];
            const allowedUsers = ['Lasim', 'JasonKrik'];
            
            const issue = context.payload.issue;
            const actor = context.actor;
            
            // Check if the action involves a protected label
            const labels = issue.labels.map(label => label.name);
            const hasProtectedLabel = protectedLabels.some(label => labels.includes(label));
            
            if (hasProtectedLabel && !allowedUsers.includes(actor)) {
              // Remove the protected label
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                name: protectedLabels[0]
              });
              
              // Optional: Comment on the issue
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: `The label "${protectedLabels[0]}" can only be added by repository maintainers.`
              });
            }